sudo: required
dist: trusty
env:
  - PATH=${HOME}/node-v6.9.1-linux-x64/bin:${PATH}
language: java
jdk:
  - oraclejdk8
before_install:
  # Correct rake bug
  - RAKE=`which rake`
  - mv `which rake` `which rake`.old
  - touch ${RAKE}
  - chmod 755 ${RAKE}
  - cd ${HOME} && wget https://nodejs.org/dist/v6.9.1/node-v6.9.1-linux-x64.tar.xz
  - cd ${HOME} && tar xfJ node-v6.9.1-linux-x64.tar.xz
  - cd ${HOME} && ls -lrt ${HOME}/node-v6.9.1-linux-x64/bin
install:
  # Npm
  - node --version
  - npm --version
  # Cf. https://github.com/angular/angular-cli#updating-angular-cli
  - npm uninstall -g angular-cli
  - npm uninstall --save-dev angular-cli
  - npm uninstall -g @angular/cli
  - npm cache clean
  - npm install -g @angular/cli@latest
  # Angular
  - cd $TRAVIS_BUILD_DIR/jarvis-core/jarvis-core-ui-ng
  - rm -rf node_modules
  - npm install @angular/cli@1.0.1
  - npm install
  - npm update
  - ng build --aot --prod --base-href /nui/ --output-path=src/main/resources/public/nui
  - rm -f $TRAVIS_BUILD_DIR/jarvis-core/jarvis-core-ui-ng/src/main/resources/public/nui/*.map
  - rm -f $TRAVIS_BUILD_DIR/jarvis-core/jarvis-core-ui-ng/src/main/resources/public/nui/*.gz
  - ls -lrt $TRAVIS_BUILD_DIR/jarvis-core/jarvis-core-ui-ng/src/main/resources/public/nui
  # Java
  - cd $TRAVIS_BUILD_DIR/jarvis-core
  - java -version
  - mvn -q install
cache:
  directories:
    - $(npm config get prefix)
    - $TRAVIS_BUILD_DIR/jarvis-core/jarvis-core-ui-ng/node_modules
deploy:
  provider: releases
  overwrite: true
  api_key: "$GITHUB_OAUTH2_KEY"
  file:
  - "${TRAVIS_BUILD_DIR}/jarvis-scripts/jarvis-service"
  - "${TRAVIS_BUILD_DIR}/jarvis-core/jarvis-core-server/src/test/resources/sample.json"
  - "${TRAVIS_BUILD_DIR}/jarvis-core/jarvis-core-server/target/jarvis-core-server-0.0.1-SNAPSHOT.jar"
  - "${TRAVIS_BUILD_DIR}/jarvis-core/jarvis-rest-module-dio/target/jarvis-rest-module-dio-0.0.1-SNAPSHOT.jar"
  - "${TRAVIS_BUILD_DIR}/jarvis-core/jarvis-rest-module-voice/target/jarvis-rest-module-voice-0.0.1-SNAPSHOT.jar"
  - "${TRAVIS_BUILD_DIR}/jarvis-core/jarvis-rest-module-exec/target/jarvis-rest-module-exec-0.0.1-SNAPSHOT.jar"
  - "${TRAVIS_BUILD_DIR}/jarvis-core/jarvis-rest-module-aiml/target/jarvis-rest-module-aiml-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_deploy: echo "deploiement termin√©"
